name: cicerone
channels:
  - bcminch
  - defaults
  - conda-forge
dependencies:
  - feather-format
  - keras
  - mars_lab
  - matplotlib
  - nb_conda_kernels
  - nodejs
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - selenium
  - tensorflow
  - pip:
    - textgenrnn
